### ISSUE TITLE
mHdmiCurrent

### ISSUE THREAD

**Issue by ChrisN812** [eousphoros/android_hardware_samsung_slsi_exynos5-insignal#1]
Getting an error on compiling with master branch with cm-12 code:

hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp: In member function 'virtual void android::ExynosHWCService::setHdmiResolution(int, int)':
hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp:195:31: error: 'ExynosHWCCtx' has no member named 'mHdmiCurrentPreset'
         resolution = mHWCCtx->mHdmiCurrentPreset;
                               ^
hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp:199:22: error: 'ExynosHWCCtx' has no member named 'mHdmiCurrentPreset'
         if (mHWCCtx->mHdmiCurrentPreset == resolution)
                      ^
hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp:201:18: error: 'ExynosHWCCtx' has no member named 'mHdmiPreset'
         mHWCCtx->mHdmiPreset = resolution;
                  ^
hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp:245:14: error: 'ExynosHWCCtx' has no member named 'mHdmiPreset'
     mHWCCtx->mHdmiPreset = resolution;
              ^
hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp: In member function 'virtual void android::ExynosHWCService::getHdmiResolution(uint32_t*, uint32_t*)':
hardware/samsung_slsi/exynos5-insignal/libhwcService/ExynosHWCService.cpp:335:22: error: 'ExynosHWCCtx' has no member named 'mHdmiCurrentPreset'
     switch (mHWCCtx->mHdmiCurrentPreset)

Noticed this code is available in libtv_primary/ExynosHWC .  Why two different ExynosHWC.h files? 

Thank you

**Comment by eousphoros** [comment]
This repo is legacy and not actively maintained. However this issue appears similar to the fix in this thread. Please take a look. Hope it helps.

http://forum.xda-developers.com/showpost.php?p=58587893&postcount=213

**Comment by noob1211** [comment]
what is causing this issue? i'm getting the same problem?
